services:
  frontend:
    build:
      context: ./Markov-GUI
    ports:
      - 3000:3000
    environment:
      - 'OPENAI_API_HOST=http://localhost:8889'
      - 'OPENAI_API_TYPE=azure'
  nginx:
    image: nginx:latest
    ports:
      - "3003:80"
    security_opt:
      - seccomp:~/seccomp/seccomp.json
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./html:/etc/nginx/html
    depends_on:
      - frontend
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1G
        reservations:
          cpus: '1'
          memory: 1G
